### ISSUE TITLE
Hi! is this a mistake or am I doing something wrong?

### ISSUE THREAD

**Issue by gekzakm** [silver-zepp/zeppos-draw#1]
draw.line({x: 50, y: 50}, {x: 400, y: 400}, { width: 4, color: multiplyHexColor(COLOR_GREEN, 0.7), group: group });
 draw.circle(400, 400,{radius: 8, color: multiplyHexColor(COLOR_GREEN, 1.5), group: group});

as a result, I get this result. It seemed to me that the point should be at the end of the line, because they have the same coordinates.
![1710997047283](https://github.com/silver-zepp/zeppos-draw/assets/36265427/40f9aaf0-31c9-4f06-a708-46e23c386e0c)

**Comment by silver-zepp** [comment]
Use `line_fix: true` param: 

> draw.line({x: 50, y: 50}, {x: 400, y: 400}, { line_fix: true, width: 4, color: multiplyHexColor(COLOR_GREEN, 0.7), group: group });

The original `FILL_RECT` widget is heavily bugged and you have to use a bugfix in some places to go around it.

**Comment by gekzakm** [comment]
if (options.line_fix) {
      let correction_factor = 1;
      let correction_angle = 25;
      **let shift = (1*Math.max(point_b.x,point_b.y))/10;**
this may not be correct, but this is how I was able to solve my problem temporarily.
